version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Laravel
      - "5173:5173"  # Vite
    volumes:
      - ./API:/var/www/API
      - ./Front-End:/var/www/Front-End
